### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by Yizzzzzzzzz** [zhouhuichen741/dalamud-plugins#1]
你好，想请问下，国服在添加了https://raw.fastgit.org/zhouhuichen741/dalamud-plugins/master/repo_cn.json之后，为啥插件都是安装失败
![image](https://github.com/zhouhuichen741/dalamud-plugins/assets/80310035/aff3e200-3345-4eb8-95bb-e4c5b3fc0732)

**Comment by zhouhuichen741** [comment]
国内仓库换地方了,忘记更新了

**Comment by Yizzzzzzzzz** [comment]
感谢
